<?php

namespace AppBundle\Repository;

/**
 * Account_FollowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Account_FollowerRepository extends \Doctrine\ORM\EntityRepository
{
}
