app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

account:
    type:     rest
    resource: AppBundle\Controller\AccountController

client:
    type:     rest
    resource: AppBundle\Controller\ClientController
